version: '3.8'

services:
  admin:
    build: 
      context: ./Ballot_System_AdminV2
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - ./Ballot_System_AdminV2/.env
    volumes:
      - ./Ballot_System_AdminV2/app:/var/www/html/app
      - ./Ballot_System_AdminV2/config:/var/www/html/config
      - ./Ballot_System_AdminV2/database:/var/www/html/database
      - ./Ballot_System_AdminV2/resources:/var/www/html/resources
      - ./Ballot_System_AdminV2/routes:/var/www/html/routes
      - ./Ballot_System_AdminV2/storage:/var/www/html/storage
    networks:
      - ballot-network
    depends_on:
      - mysql

  voter:
    build:
      context: ./Ballot_System_VoterV2
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    env_file:
      - ./Ballot_System_VoterV2/.env
    volumes:
      - ./Ballot_System_VoterV2/app:/var/www/html/app
      - ./Ballot_System_VoterV2/config:/var/www/html/config
      - ./Ballot_System_VoterV2/database:/var/www/html/database
      - ./Ballot_System_VoterV2/resources:/var/www/html/resources
      - ./Ballot_System_VoterV2/routes:/var/www/html/routes
      - ./Ballot_System_VoterV2/storage:/var/www/html/storage
    networks:
      - ballot-network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql_docker
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ballot_system_adminv2
      MYSQL_USER: ballot_user
      MYSQL_PASSWORD: ballot_password
    volumes:
      - db-data:/var/lib/mysql
      - ./sql/ballot_system_adminv2.sql:/docker-entrypoint-initdb.d/ballot_system_adminv2.sql
    networks:
      - ballot-network

networks:
  ballot-network: {}

volumes:
  db-data: {}
